# settings.py

# =========================
# CONFIGURACIÓN DE PANTALLA
# =========================

ANCHO_PANTALLA = 1280
ALTO_PANTALLA = 720
FPS = 60

TITULO_JUEGO = "Cyber Python"


# =========================
# COLORES RGB
# =========================

NEGRO = (10, 10, 18)
BLANCO = (255, 255, 255)
VERDE_CYBER = (0, 255, 120)
AZUL_CYBER = (0, 180, 255)
ROJO_ALERTA = (255, 60, 60)
AMARILLO = (255, 220, 80)
GRIS_OSCURO = (35, 35, 45)
GRIS_CLARO = (160, 160, 170)
MORADO_CYBER = (180, 80, 255)


# =========================
# JUGADOR
# =========================

VELOCIDAD_JUGADOR = 5
ANCHO_JUGADOR = 120
ALTO_JUGADOR = 144

VIDAS_INICIALES = 3
ENERGIA_INICIAL = 100


# =========================
# DISPAROS
# =========================

VELOCIDAD_BALA = 8
ANCHO_BALA = 6
ALTO_BALA = 14


# =========================
# ENEMIGOS
# =========================

VELOCIDAD_ENEMIGO = 2
ANCHO_ENEMIGO = 95
ALTO_ENEMIGO = 95

PUNTOS_ENEMIGO_PEQUENO = 10
PUNTOS_ENEMIGO_MEDIANO = 50
PUNTOS_FINAL_BOSS = 500

# =========================
# ESTADOS DEL JUEGO
# =========================

ESTADO_MENU = "menu"
ESTADO_JUGANDO = "jugando"
ESTADO_PAUSA = "pausa"
ESTADO_GAME_OVER = "game_over"
ESTADO_VICTORIA = "victoria"
ESTADO_INTRO = "intro"

# =========================
# POWER-UPS
# =========================

# Escáner
DURACION_SCANNER_MS = 1200
VELOCIDAD_EXPANSION_SCANNER = 18

# Arma poderosa
CADENCIA_ARMA_NORMAL_MS = 180
CADENCIA_ARMA_PODEROSA_MS = 50
MUNICION_ARMA_PODEROSA_POR_POWERUP = 100

ANCHO_BALA_PODEROSA = 18
ALTO_BALA_PODEROSA = 42
VELOCIDAD_BALA_PODEROSA = 7

DANIO_BALA_NORMAL = 1
DANIO_BALA_PODEROSA = 3

# Aliados
CANTIDAD_ALIADOS = 4
DURACION_ALIADOS_MS = 5000
CADENCIA_DISPARO_ALIADO_MS = 450

# =========================
# OLEADAS ENEMIGAS
# =========================

ENEMIGOS_POR_OLEADA_MIN = 4
ENEMIGOS_POR_OLEADA_MAX = 10

SEPARACION_ENEMIGOS_OLEADA = 55

DURACION_ENTRADA_OLEADA_MS = 2600
DURACION_ESCAPE_OLEADA_MS = 1800

INTERVALO_OLEADAS_MS = 3500

DISTANCIA_ATAQUE_CERCA_JUGADOR = 120

# =========================
# FASES DE COMBATE
# =========================

OLEADAS_ANTES_TORMENTA_METEORITOS = 10

TOTAL_METEORITOS_TORMENTA = 50
INTERVALO_METEORITOS_TORMENTA_MS = 120

# =========================
# FINAL BOSS - DERROTA Y VICTORIA
# =========================

DURACION_TEMBLOR_ENTRADA_BOSS_MS = 3000
DURACION_REMOLINO_ENTRADA_BOSS_MS = 1800
INTENSIDAD_TEMBLOR_ENTRADA_BOSS = 10

DURACION_EXPLOSIONES_FINAL_BOSS_MS = 5000
INTERVALO_EXPLOSIONES_FINAL_BOSS_MS = 180
RETRASO_TRANSICION_VICTORIA_MS = 800

# =========================
# INTRO / DESPEGUE INICIAL
# =========================

DURACION_INTRO_ESPERA_MS = 12500
DURACION_INTRO_DESPEGUE_MS = 9000

INTRO_DIALOGO_SLIDE_MS = 450
INTRO_DIALOGO_HOLD_MS = 3000

INTRO_DIALOGO_ANCHO = 560
INTRO_DIALOGO_ALTO = 292

INTRO_DIALOGO_RUTA_BASE = "assets/images/dialogs"

INTRO_DIALOGO_MARGEN_LATERAL = 40
INTRO_DIALOGO_MARGEN_SUPERIOR = 35

# Sprites de la escena de intro
INTRO_SPRITES_RUTA_BASE = "assets/images/intro"

INTRO_TIERRA_IMAGEN = "intro_earth.png"
INTRO_ESTACION_FONDO_IMAGEN = "intro_station_back.png"
INTRO_ESTACION_FRENTE_IMAGEN = "intro_station_front.png"

INTRO_TIERRA_ANCHO = 720
INTRO_TIERRA_ALTO = 720
INTRO_TIERRA_CENTRO_Y = 130

INTRO_ESTACION_ANCHO = 1280
INTRO_ESTACION_ALTO = 720
INTRO_ESTACION_FONDO_Y = 70
INTRO_ESTACION_FRENTE_Y = 70

INTRO_ESTACION_COMPLETA_EN_PROGRESO = 0.45
INTRO_MARGEN_SALIDA_SPRITES = 100
INTRO_JUGADOR_Y = ALTO_PANTALLA - 210

INTRO_VELOCIDAD_LUZ_ALTO_EFECTO = 180
INTRO_VELOCIDAD_LUZ_CANTIDAD_ESTRELLAS = 95
INTRO_VELOCIDAD_LUZ_INICIO_FADE_PROGRESO = 0.82
DURACION_VELOCIDAD_LUZ_JUGANDO_MS = 2800




# =========================
# DIALOGOS POR IMAGEN
# =========================
DIALOG_IMAGE_WIDTH = 460
DIALOG_IMAGE_HEIGHT = 240

DIALOG_MARGIN_X = 30
DIALOG_MARGIN_Y = 20

DIALOG_HOLD_TIME = 3.0
DIALOG_SLIDE_SPEED = 900

DIALOG_LEFT = "left"
DIALOG_RIGHT = "right"
