sonar.projectKey=cyber-python
sonar.projectName=cyber-python
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=.venv/**,venv/**,__pycache__/**,.git/**,.github/**,assets/**,evidence/**,screenshots/**

sonar.python.version=3.9

sonar.sourceEncoding=UTF-8
